name: Java CI with Gradle

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Maven
      run: mvn clean package
    - name: artifact
      uses: actions/upload-artifact@v3   
      with:
        name: Build
        path: target/*
